# -*- coding: utf-8 -*-
"""HandsOn1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1weWj_CkZeuNQgZF1UwXpm2qHRCkOBjH8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# dataset has 15 columns and 2392 students
df = pd.read_csv("Student_performance_data _.csv")

#Note, this is to delete Gradeclass if GPA is what I am after
df = df.drop(columns=["GradeClass"]) #It is the opposite of GPA

#Other notes: Ethnicity (0=Caucasian, 1=African American, 2=Asian, 3=Other);
#             ParentalEducation (0=None, 1=High School, 2=Some College, 3=Bachelor’s, 4=Higher); ParentalSupport (0=None, 1=Low, 2=Moderate, 3=High, 4=Very High).

# Head of dataset
df.head()

# Shape of dataset
print("Dataset Shape:", df.shape)

# Column names
print("\nColumns:\n", df.columns)

# Data types
print("\nData Types:\n")
print(df.dtypes)

df.describe(include='all') #statistics

# Check missing values
missing_values = df.isnull().sum()
print("Missing Values in each Column:\n")
print(missing_values)

#no missing values

print("Number of duplicate rows is:", df.duplicated().sum())# no duplicate rows

import seaborn as sns
import matplotlib.pyplot as plt
# this is a correlation matrix
plt.figure(figsize=(10,8))
sns.heatmap(df.corr(), annot=False, cmap="coolwarm")
plt.show()

#this shows that Abscneces is blue beucase its bad(so look for no), and tutoring, studytime, and parental support are redish

#need to make a scattergraph:

import matplotlib.pyplot as plt #imot

plt.figure(figsize=(8,6))
plt.scatter(df['StudyTimeWeekly'], df['GPA'], alpha=0.6)
plt.xlabel('Study Time Weekly')
plt.ylabel('GPA')
plt.title('Study Time Weekly vs GPA')
plt.show()

# a second idea would be the absecnes one

plt.figure(figsize=(8,6))
plt.scatter(df['Absences'], df['GPA'], alpha=0.6, color='red')
plt.xlabel('Absences')
plt.ylabel('GPA')
plt.title('Absences vs GPA')
plt.show()

#this one is better becuase it shows a relationship

from sklearn.linear_model import LinearRegression

reg = LinearRegression()
reg.fit(df[['Absences']], df['GPA'])

reg.predict([[12]]) # the less, the better the GPA

#this is the predictions that is for the first algorithm
import pandas as pd

# load as d
d = pd.read_csv("Student_performance_data _.csv")

# Make predictions for p
p = reg.predict(d[['Absences']])

# Add predictions to dataframe
d['Predicted-GPA'] = p

# Save results
d.to_csv('predictions.csv', index=False)

# Head the results
e = pd.read_csv("predictions.csv")
e.head()
#sent to other excel sheet

import matplotlib.pyplot as plt

# Scatter plot
plt.xlabel('Absences')
plt.ylabel('GPA')
plt.scatter(df['Absences'], df['GPA'], color='red', marker='+')

# Regression line
plt.plot(df['Absences'], reg.predict(df[['Absences']]), color='blue')

plt.show() #tried to change the predict, but had some problems that were hard to fix

import pandas as pd

# Load your dataset (change filename if needed)
#df = pd.read_csv("students.csv")

# Features (X) and Target (y)
X = df[['Absences', 'StudyTimeWeekly']]   # chose the predictors
y = df['GPA']   # target is GPA

# Split dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Here is the Linear Regression model
from sklearn.linear_model import LinearRegression #(again)

clf = LinearRegression()
clf.fit(X_train, y_train)

# Now for the Make predictions
y_pred = clf.predict(X_test)
y_pred

#  Check score
print("The Score: ", clf.score(X_test, y_test))

# Need a Pass or Fail column based on GPA
df["Pass"] = np.where(df["GPA"] >= 2.5, 1, 0)

# The passs or faill
X = df.drop(columns=["GPA", "Pass"])
y = df["Pass"]

# test and train
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Here is the Linear Regression model
from sklearn.linear_model import LinearRegression #(again)

clf = LinearRegression()
clf.fit(X_train, y_train)

# Now for the Make predictions
y_pred = clf.predict(X_test)
y_pred

#  Check score
print("The Score: ", clf.score(X_test, y_test))

from sklearn.metrics import classification_report

#print(classification_report(y_test, y_pred) )

# Actual Pass/Fail
plt.scatter(df.loc[X_test.index, "Absences"], df.loc[X_test.index, "GPA"], c=y_test)
plt.xlabel("Absences")
plt.ylabel("GPA")
plt.show()

# The Predicted Pass/Fail
plt.scatter(df.loc[X_test.index, "Absences"], df.loc[X_test.index, "GPA"], c=y_pred)
plt.xlabel("Absences")
plt.ylabel("GPA")
plt.show()

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
cm

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred) )